### ISSUE TITLE
Fragen zur Kodierung

### ISSUE THREAD

**Issue by Honoka10** [mgoermar/vogel_florilegium_genealogicum#2]
**- Irreguläre Schreibrichtung (gedreht)**

Ich denke, dass man dies auf die gleiche Weise wie andere schreiben kann, und es sollte darauf hingewiesen werden. Allerdings bin ich mir nicht ganz sicher.

![image](https://github.com/mgoermar/vogel_florilegium_genealogicum/assets/151395670/cf7e107f-3ca6-423c-a827-252481b23efb)

**- Farbunterschied der Tinte**

Sollte der Farbunterschied auch erwähnt werden?

![image](https://github.com/mgoermar/vogel_florilegium_genealogicum/assets/151395670/7833572f-a519-42e4-9488-99f6b795a4b9)

(Honoka Oka)

**Comment by mgoermar** [comment]
Zunächst zum Farbunterschied: Den würde ich an dieser Stelle unberücksichtigt lassen, da sich die Ergänzungen so, wie es auf dem Screenshot aussieht, ansonsten nahtlos in den Stammbaum einfügen.

Bei Änderungen der Schreibrichtung würde ich grundsätzlich eine Anmerkung für den Textapparat setzen, in etwa so:
`<note type="annotation" resp="mg">Schreibrichtung im Verhältnis zum sonstigen Text um ca. 90 Grad gedreht.</note>`
Wenn es sich erkennbar um eine nachträgliche Hinzufügung handelt, sollte der entsprechende Text zudem als solche kodiert werden, also mit:
`<add place="inline">...</add>`
