### ISSUE TITLE
Bleistiftnotizen kodieren

### ISSUE THREAD

**Issue by Taohua-Yuan** [mgoermar/vogel_florilegium_genealogicum#3]
Im Falle des von mir ausgewählten Stammbaumes sind spätere Bleistifteinträge vorhanden, welche nicht von Vogel stammen (siehe Anhang). Sollen auch diese transkribiert werden und wenn ja, auf welche Weise?
![Bildschirmfoto vom 2024-01-14 23-17-03](https://github.com/mgoermar/vogel_florilegium_genealogicum/assets/150633411/d857a05d-526f-470a-811c-fd1da569f134)

**Comment by mgoermar** [comment]
Ich würde wie folgt kodieren:
`<add place="inline"><handShift/>...</add><note type="annotation" resp="fm">Spätere Bleistiftnotiz.</note>
...
<handShift scribe="vogel"/>`
