### ISSUE TITLE
Frage Transkription Moebius

### ISSUE THREAD

**Issue by lr30kery** [mgoermar/vogel_florilegium_genealogicum#4]
Ich habe eine Frage zu folgender Stelle im Stammbaum der Familie Moebius.
Wie kann dies transkribiert werden?

<img width="334" alt="Frage_Transkription" src="https://github.com/mgoermar/vogel_florilegium_genealogicum/assets/151474792/6e92f6f3-f643-4215-b985-cd99c25c0dc5">

**Comment by mgoermar** [comment]
Osterhausen

(In der Sitzung hatten wir in der GND ja auch eine Reihe von Trägern dieses Namens gefunden. Man müsste hier nochmal schauen, wer genau gemeint ist.)
