### ISSUE TITLE
Frage Transkription Thomasius

### ISSUE THREAD

**Issue by jjmmww** [mgoermar/vogel_florilegium_genealogicum#5]
Folgende Textstelle ist problematisch
<img width="219" alt="Bildschirmfoto 2024-01-15 um 09 31 19" src="https://github.com/mgoermar/vogel_florilegium_genealogicum/assets/150660486/a3396c10-71c9-400b-b7ce-6409a9822dcd">

**Comment by jjmmww** [comment]
Gleiches Problem:
<img width="374" alt="Bildschirmfoto 2024-01-15 um 09 38 37" src="https://github.com/mgoermar/vogel_florilegium_genealogicum/assets/150660486/7db317ea-3c9d-4da4-a40f-e9e929a0d96d">

**Comment by mgoermar** [comment]
Die erste Stelle ist als "Erbh[err]" zu transkribieren bzw. so zu kodieren:
`Erbh<ex>err</ex>`

Bei der zweiten Stelle, hatten Sie ja dann selber noch die Lösung gefunden. Vielleicht können Sie sie noch posten?

**Comment by jjmmww** [comment]
Pfretzschner(in)
